/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto1.pkg4;



/**
 *
 * @author gabriellavetencourt
 */
public class Agregar extends javax.swing.JFrame {

    /**
     * Creates new form Agregar
     */
    private Mapa m;
    
    
   
    

    public Agregar(Mapa m) {

        initComponents();

        this.setTitle("Amazon");
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        this.m = m;
        this.aggAlmacen.setEnabled(false);
        this.jMenu3.setEnabled(false);
        this.jButton3.setEnabled(false);
        
        

    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        Archivo = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        aggAlmacen = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        AggRuta = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        gestionStock = new javax.swing.JMenuItem();
        comprar = new javax.swing.JMenuItem();
        reporteDisp = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setText("Cargar Archivo");

        Archivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ArchivoActionPerformed(evt);
            }
        });

        aggAlmacen.setText("Agregar");

        jMenuItem1.setText("Almacen");
        jMenuItem1.addMenuKeyListener(new javax.swing.event.MenuKeyListener() {
            public void menuKeyPressed(javax.swing.event.MenuKeyEvent evt) {
            }
            public void menuKeyReleased(javax.swing.event.MenuKeyEvent evt) {
                jMenuItem1MenuKeyReleased(evt);
            }
            public void menuKeyTyped(javax.swing.event.MenuKeyEvent evt) {
            }
        });
        jMenuItem1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuItem1MouseClicked(evt);
            }
        });
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        aggAlmacen.add(jMenuItem1);

        AggRuta.setText("Ruta");
        AggRuta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AggRutaActionPerformed(evt);
            }
        });
        aggAlmacen.add(AggRuta);

        jMenuBar1.add(aggAlmacen);

        jMenu3.setText("Gestionar Productos");
        jMenu3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu3ActionPerformed(evt);
            }
        });

        gestionStock.setText("Gestión de Stock");
        gestionStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gestionStockActionPerformed(evt);
            }
        });
        jMenu3.add(gestionStock);

        comprar.setText("Comprar");
        comprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comprarActionPerformed(evt);
            }
        });
        jMenu3.add(comprar);

        reporteDisp.setText("Reporte de Disponibilidad");
        reporteDisp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reporteDispActionPerformed(evt);
            }
        });
        jMenu3.add(reporteDisp);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(434, 434, 434)
                .addComponent(Archivo, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addContainerGap(509, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(630, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Archivo, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(322, 322, 322))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        new AgregarAlmacen(m).setVisible(true);


    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void AggRutaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AggRutaActionPerformed
        // TODO add your handling code here:
        new AgregarRuta(m).setVisible(true);


    }//GEN-LAST:event_AggRutaActionPerformed

    private void jMenuItem1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem1MouseClicked
        // TODO add your handling code here:


    }//GEN-LAST:event_jMenuItem1MouseClicked

    private void jMenuItem1MenuKeyReleased(javax.swing.event.MenuKeyEvent evt) {//GEN-FIRST:event_jMenuItem1MenuKeyReleased
        // TODO add your handling code here:
        //  new AgregarAlmacen().setVisible(true);
    }//GEN-LAST:event_jMenuItem1MenuKeyReleased

    private void ArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ArchivoActionPerformed
        // TODO add your handling code here:
        
         
        
        Cargar cargar=new Cargar(m, this);
        cargar.setVisible(true);


    }//GEN-LAST:event_ArchivoActionPerformed

    private void gestionStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gestionStockActionPerformed
        // TODO add your handling code here:
     new GestionarStock(m).setVisible(true);
    }//GEN-LAST:event_gestionStockActionPerformed

    private void jMenu3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu3ActionPerformed
        // TODO add your handling code here:
     
        
    }//GEN-LAST:event_jMenu3ActionPerformed

    private void comprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comprarActionPerformed
        // TODO add your handling code here:
        
         new Compra(m).setVisible(true);
         
        
        
    }//GEN-LAST:event_comprarActionPerformed

    private void reporteDispActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reporteDispActionPerformed
        // TODO add your handling code here:
         new Recorrido(m).setVisible(true);
         
    }//GEN-LAST:event_reporteDispActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Agregar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Agregar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Agregar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Agregar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        Mapa m = new Mapa();
        Agregar a = new Agregar(m);
        a.setContentPane(m);
        a.setSize(1000, 800);
        a.setLocationRelativeTo(null);


        a.setVisible(true);

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem AggRuta;
    private javax.swing.JButton Archivo;
    public javax.swing.JMenu aggAlmacen;
    private javax.swing.JMenuItem comprar;
    private javax.swing.JMenuItem gestionStock;
    public javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel2;
    public javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem reporteDisp;
    // End of variables declaration//GEN-END:variables

}
