/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto1.pkg4;


import javax.swing.*;

/**
 *
 * @author gabriellavetencourt
 */
public class GestionarStock extends javax.swing.JFrame {

    /**
     * Creates new form Cargar
     */
    String nombre;
    Mapa m;
    String contenido = "";
    String nombreAux;
    int cantidad;

    public GestionarStock(Mapa m) {
        initComponents();
        this.setResizable(false);
        this.setTitle("Gestionar Stock");
        this.m = m;
        this.jTextArea1.setEditable(false);
        this.modificar.setVisible(false);
        this.aggNuevo.setVisible(false);
        this.volver.setVisible(false);
        this.inputProducto.setVisible(false);
        this.inputCant.setVisible(false);
        this.jLabel1.setVisible(false);
        this.jLabel3.setVisible(false);
        this.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
    }

    //cuando escoges el almacen esto imprime los productos existentes en el y su cantidad
    private void Imprimir(int almacen) {
        contenido = "";
        System.out.println("llegue");
        if (!m.getGrafo().getAlmacenes()[almacen].getProductos().EsVacio()) {
            Producto aux = m.getGrafo().getAlmacenes()[almacen].getProductos().getpFirst();
            for (int j = 0; j < m.getGrafo().getAlmacenes()[almacen].getProductos().getSize(); j++) {
                System.out.print(aux.getNombre() + " ");

                contenido += aux.getNombre() + "    Cantidad: " + Integer.toString(aux.getCantidad()) + "\n";

                aux = aux.getPnext();

            }

        }
        jTextArea1.setText(contenido);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPaneProductos = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        buscarAlmacen = new javax.swing.JButton();
        inputAlmacen = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        inputProducto = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        inputCant = new javax.swing.JTextField();
        aggNuevo = new javax.swing.JButton();
        modificar = new javax.swing.JButton();
        volver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPaneProductos.setViewportView(jTextArea1);

        buscarAlmacen.setText("Buscar Almacen");
        buscarAlmacen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarAlmacenActionPerformed(evt);
            }
        });

        jLabel1.setText("Nombre del Producto");

        jLabel2.setText("Nombre del Almacen");

        jLabel3.setText("Cantidad Del Producto");

        aggNuevo.setText("Agregar Nuevo");
        aggNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aggNuevoActionPerformed(evt);
            }
        });

        modificar.setText("Modificar");
        modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarActionPerformed(evt);
            }
        });

        volver.setText("Volver");
        volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(inputAlmacen)
                    .addComponent(jLabel1)
                    .addComponent(buscarAlmacen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2)
                    .addComponent(inputProducto)
                    .addComponent(jLabel3)
                    .addComponent(inputCant)
                    .addComponent(aggNuevo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(modificar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(volver, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(28, 28, 28)
                .addComponent(jScrollPaneProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputAlmacen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(buscarAlmacen))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(inputCant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(modificar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(aggNuevo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(volver)
                .addContainerGap(13, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPaneProductos)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void buscarAlmacenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarAlmacenActionPerformed
        try {

            nombre = this.inputAlmacen.getText();

            if (this.inputAlmacen.getText() == null) {
                JOptionPane.showMessageDialog(this, "Por favor ingrese el nombre del producto.");
            }
            System.out.println("");
            if (m.getGrafo().buscarAlmacen(nombre) != null) {

                this.Imprimir(m.getGrafo().getIndex(nombre));

                this.inputProducto.setVisible(true);
                this.inputAlmacen.setVisible(false);
                this.jLabel2.setVisible(false);
                this.buscarAlmacen.setVisible(false);
                this.inputCant.setVisible(true);
                this.jLabel1.setVisible(true);
                this.jLabel3.setVisible(true);
                this.aggNuevo.setVisible(true);
                this.modificar.setVisible(true);
                this.volver.setVisible(true);
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Algo salio mal.");
        }

    }//GEN-LAST:event_buscarAlmacenActionPerformed

    private void aggNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aggNuevoActionPerformed
        // TODO add your handling code here:
        boolean found = false;
        try {

            nombreAux = this.inputProducto.getText();
            cantidad = Integer.parseInt(this.inputCant.getText());

            if (this.inputProducto.getText() == null && this.inputCant.getText() != null) {
                JOptionPane.showMessageDialog(this, "Por favor ingrese el nombre del producto.");
            }
            if (cantidad > 0) {
                if (!m.getGrafo().getAlmacenes()[m.getGrafo().getIndex(nombre)].getProductos().EsVacio()) {
                    Producto aux = m.getGrafo().getAlmacenes()[m.getGrafo().getIndex(nombre)].getProductos().getpFirst();
                    for (int j = 0; j < m.getGrafo().getAlmacenes()[m.getGrafo().getIndex(nombre)].getProductos().getSize(); j++) {
                        if (nombreAux.equalsIgnoreCase(aux.getNombre())) {
                            found = true;
                            break;
                        }

                        aux = aux.getPnext();

                    }

                }
                if (!found) {
                    System.out.println("Encontado");
                    m.getGrafo().buscarAlmacen(nombre).getProductos().InsertarFinal(nombreAux, cantidad);
                } else {
                    JOptionPane.showMessageDialog(this, "No se puede agregar este producto debido a que ya existe.");
                }

                inputProducto.setText("");
                inputCant.setText("");

                this.Imprimir(m.getGrafo().getIndex(nombre));
            } else {
                JOptionPane.showMessageDialog(this, "Ingrese un número positivo.");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Por favor ingrese una cantidad valida.");
        }
    }//GEN-LAST:event_aggNuevoActionPerformed

    //cambia la cantidad de un producto existente
    private void modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarActionPerformed
        // TODO add your handling code here:
        try {
            boolean found = false;
            nombreAux = this.inputProducto.getText();
            cantidad = Integer.parseInt(this.inputCant.getText());
            System.out.println("kkk" + nombreAux);
            if (cantidad > 0) {
                if (!m.getGrafo().getAlmacenes()[m.getGrafo().getIndex(nombre)].getProductos().EsVacio()) {
                    Producto aux = m.getGrafo().getAlmacenes()[m.getGrafo().getIndex(nombre)].getProductos().getpFirst();
                    for (int j = 0; j < m.getGrafo().getAlmacenes()[m.getGrafo().getIndex(nombre)].getProductos().getSize(); j++) {
                        if (nombreAux.equalsIgnoreCase(aux.getNombre())) {
                            found = true;
                            break;
                        }

                        aux = aux.getPnext();

                    }
                    if (found) {
                        System.out.println("Encontado");
                        aux.setCantidad(cantidad);
                        this.Imprimir(m.getGrafo().getIndex(nombre));
                    } else {
                        JOptionPane.showMessageDialog(this, "Por favor ingrese un producto que exista.");
                    }
                }
            } else {

                JOptionPane.showMessageDialog(this, "Ingrese un número positivo.");

            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Algo salió mal.");
        }

    }//GEN-LAST:event_modificarActionPerformed

    private void volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverActionPerformed
        // TODO add your handling code here:
        this.modificar.setVisible(false);
        this.aggNuevo.setVisible(false);
        this.volver.setVisible(false);
        this.inputProducto.setVisible(false);
        this.inputCant.setVisible(false);
        this.jLabel1.setVisible(false);
        this.jLabel3.setVisible(false);
        this.inputAlmacen.setVisible(true);
        this.jLabel2.setVisible(true);
        this.buscarAlmacen.setVisible(true);

    }//GEN-LAST:event_volverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionarStock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionarStock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionarStock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionarStock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aggNuevo;
    private javax.swing.JButton buscarAlmacen;
    private javax.swing.JTextField inputAlmacen;
    private javax.swing.JTextField inputCant;
    private javax.swing.JTextField inputProducto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPaneProductos;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JButton modificar;
    private javax.swing.JButton volver;
    // End of variables declaration//GEN-END:variables
}
